### PR TITLE
Add multi face recognition

### PR DESCRIPTION
**Pull request by siddharth595**
Multi-face detection has been implemented and is working well. I have also added a couple of features of the binding of Enter key to submit the image and handle the error while a wrong link is passed to the Clarifai API. Please look into it and let me know if some changes are required, thankyou!

image

image

### CODE REVIEW

**Comment by muhammadsuheer** [comment]
@siddharth595 Thank You SO Much It's Working great

**Comment by siddharth595** [comment]
@muhammadsuheer I am participating in Hacoberfest2022. So could you please label the repository or the pr as mentioned below? It would be of great help to me
image

**Comment by siddharth595** [comment]
@muhammadsuheer can you please change the label to hacktoberfest-accepted. The automated system of hacktoberfest is not able to detect the repository with the minute spelling change.

**Comment by muhammadsuheer** [comment]
@siddharth595 sure

**Comment by siddharth595** [comment]
@muhammadsuheer  can you please add another label hacktoberfest-accepted to this pull request

**Comment by muhammadsuheer** [comment]
@siddharth595 can you check while running this project it's giving error

**Pull request merged**
